version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=rdb_sync
      - MYSQL_PASSWORD=rdb_sync

  starrocks:
    image: starrocks/allin1-ubuntu:latest
    container_name: starrocks
    ports:
      - '9030:9030'
      - '8080:8080'
    environment:
      - TZ=Asia/Shanghai

  flink-job-manager:
    image: flink:1.18.0-java11
    container_name: flink-job-manager
    ports:
      - '8081:8081'
    command: jobmanager
    environment:
      - TZ=Asia/Shanghai
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-job-manager        

  flink-task-manager:
    image: flink:1.18.0-java11
    container_name: flink-task-manager
    depends_on:
      - flink-job-manager
    command: taskmanager
    environment:
      - TZ=Asia/Shanghai
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-job-manager
        taskmanager.numberOfTaskSlots: 10
